### ISSUE TITLE
BigDisplay

### ISSUE THREAD

**Issue by mtrnka** [lujonathanh/PeakSeeker#1]
The option to maximize window display fails under my configuration.  Details below:

```
Traceback (most recent call last):
  File "PeakSeeker.py", line 2105, in <module>
    main()
  File "PeakSeeker.py", line 1973, in main
    figManager.window.showMaximized()
AttributeError: 'FigureManagerMac' object has no attribute 'window'
```

I am using python 2.7 on OSX

```
warangkula:PeakSeeker mtrnka$ which python
/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python
```

I have the following python packages installed (installed using pip):

```
warangkula:PeakSeeker mtrnka$ pip list
backports.ssl-match-hostname (3.4.0.2)
biopython (1.63)
matplotlib (1.3.1)
nose (1.3.3)
numpy (1.8.1)
pip (1.5.5)
pyparsing (2.0.2)
python-dateutil (2.2)
scikit-learn (0.14.1)
setuptools (3.6)
six (1.6.1)
tornado (3.2.1)
virtualenv (1.11.5)
wsgiref (0.1.2)

```

**Comment by lujonathanh** [comment]
The problem is that the default backend of matplotlib is MacOSX, which doesn't allow maximization.

You can fix this by either of the following:
1) In the PeakSeeker.py source code, add the line matplotlib.use('Qt4Agg') after the line "import matplotlib"

2) Changing your default backend parameter from MacOSX to Qt4Agg in the matplotlibrc file:
a) Get your matplotlibrc file path by adding the line "print matplotlib.matplotlib_fname()" after the line "import matplotlib" in any Python program.
b) Open the matplotlibrc file.
c) Find the line that says "backend      : MacOSX" and change it to "backend      : Qt4Agg"

See http://matplotlib.org/users/customizing.html#customizing-matplotlib for additional information.
